pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.6
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip pipenv
      pipenv install --dev --skip-lock
    displayName: 'Install prerequisites'

  - script: |
      pipenv run pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=condition_chain --cov-report=xml --cov-report=html
    displayName: 'Run tests'
  
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

  - script: |
      pipenv run python setup.py sdist bdist_wheel --universal
    displayName: 'Build'